apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-webroot
  labels:
    type: local
#  annotations:
#    pv.beta.kubernetes.io/gid: "webfiles"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv0001/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-webroot
  labels:
    app: symfony
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
